const SUPABASE_URL='https://0ec90b57d6e95fcbda19832f.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJib2x0IiwicmVmIjoiMGVjOTBiNTdkNmU5NWZjYmRhMTk4MzJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODE1NzQsImV4cCI6MTc1ODg4MTU3NH0.9I8-U0x86Ak8t2DGaIk0HfvTSLsAyzdnz-Nw00mMkKw';
const headers={'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':`Bearer ${SUPABASE_KEY}`};
const authView=document.querySelector('#authView'),mainView=document.querySelector('#mainView'),authForm=document.querySelector('#authForm'),authError=document.querySelector('#authError');
let user=null;
async function hash(value){const bytes=new TextEncoder().encode(value),buffer=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(buffer)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function request(path,options={}){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers});if(!response.ok)throw new Error('Request failed.');return response.status===204?null:response.json()}
async function login(username,password){const rows=await request(`app_users?select=id,username,role&username=eq.${encodeURIComponent(username.trim())}&password=eq.${await hash(password)}&limit=1`);return rows[0]||null}
authForm.addEventListener('submit',async event=>{event.preventDefault();authError.textContent='';const button=authForm.querySelector('button');button.disabled=true;try{user=await login(document.querySelector('#username').value,document.querySelector('#password').value);if(!user)throw new Error('Incorrect username or password.');sessionStorage.setItem('calamansi_user',JSON.stringify(user));showMain()}catch(error){authError.textContent=error.message}finally{button.disabled=false}});
document.querySelector('#registerButton').addEventListener('click',async()=>{const username=prompt('Choose a username');const password=prompt('Choose a password of at least 4 characters');if(!username||!password||password.length<4)return;try{await request('app_users',{method:'POST',body:JSON.stringify({username:username.trim(),password:await hash(password),role:'user'})});alert('Account created. You can now log in.')}catch(error){authError.textContent='That username is already taken.'}});
function showMain(){authView.classList.add('hidden');mainView.classList.remove('hidden')}
document.querySelector('#logoutButton').addEventListener('click',()=>{sessionStorage.removeItem('calamansi_user');user=null;mainView.classList.add('hidden');authView.classList.remove('hidden')});
document.querySelector('#predictButton').addEventListener('click',async()=>{const input=document.querySelector('#weightInput'),error=document.querySelector('#predictionError'),button=document.querySelector('#predictButton');const weight=Number(input.value);error.textContent='';if(!weight||weight<=0){error.textContent='Enter a weight greater than zero.';return}button.disabled=true;button.textContent='Running models...';try{const response=await fetch(`${SUPABASE_URL}/functions/v1/predict`,{method:'POST',headers,body:JSON.stringify({weight_g:weight,user_id:user.id,username:user.username,save:true})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Prediction failed.');document.querySelector('#results').classList.remove('hidden');document.querySelector('#sizeLabel').textContent=body.size_label;document.querySelector('#weightLabel').textContent=`${weight.toLocaleString()} g`;const cards=document.querySelector('#resultCards');cards.replaceChildren();body.results.forEach(result=>{const card=document.createElement('article');card.className='result-card';const title=document.createElement('h3');title.textContent=result.algorithm;const juice=document.createElement('div');juice.className='juice';juice.textContent=`${Number(result.predicted_juice).toFixed(2)} ml`;const liters=document.createElement('div');liters.className='liters';liters.textContent=`${(Number(result.predicted_juice)/1000).toFixed(4)} L`;card.append(title,juice,liters);cards.append(card)});}catch(error){document.querySelector('#predictionError').textContent=error.message}finally{button.disabled=false;button.textContent='Run all 3 models'}});
try{user=JSON.parse(sessionStorage.getItem('calamansi_user'));if(user)showMain()}catch(_){sessionStorage.removeItem('calamansi_user')}
